name: CI Build, Test, Scan and Push

on:
    push:
        branches:
            - main


    pull_request:
        branches:
            - main
        paths:
            - 'app/**'
            - '.github/workflows/ci.yaml'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions: 
  actions: read  
  contents: write  
  security-events: write  
  pull-requests: read 


jobs:
  lint:
    uses: ./.github/workflows/linter.yml 

  sast:
    uses: ./.github/workflows/codescans.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  



