name: Deprovision AWS Resources

on:
    workflow_dispatch:
        inputs:
            confirmenv:
                description: "Which env to destroy -- prod/test"
                required: true
                default: ""
                type: string



concurrency:
    group: terraform-actions
    cancel-in-progress: false

jobs:
    testenvdestroy:
        runs-on: ubuntu-latest
        if: ${{ inputs.confirmenv == 'test' }}
        defaults:
            run:
                working-directory: terraform/environments/test
        environment:
            destroy
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}    # Stored in GitHub Secrets
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Setup TF
              uses: hashicorp/setup-terraform@v3

            - name: Initialise TF
              run: terraform init

            - name: terraform destroy
              run: terraform destroy --auto-approve
    prodenvdestroy:
        runs-on: ubuntu-latest
        if: ${{ inputs.confirmenv == 'prod' }}
        defaults:
            run:
                working-directory: terraform/environments/prod
        environment:
            destroy
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}    # Stored in GitHub Secrets
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Setup TF
              uses: hashicorp/setup-terraform@v3

            - name: Initialise TF
              run: terraform init

            - name: terraform destroy
              run: terraform destroy --auto-approve
