name: Deploy to Prod

on:
    workflow_call:
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true
            AWS_REGION:
                required: true
            

concurrency:
    group: terraform-actions
    cancel-in-progress: false
    
jobs:
    proddeploy:
        environment:
            production
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: terraform/environments/prod
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS Creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}    # Stored in GitHub Secrets
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Setup TF
              uses: hashicorp/setup-terraform@v3

            - name: Format TF code
              run: terraform fmt

            - name: Initialise TF
              run: terraform init 

            - name: Validate TF code
              run: terraform validate
              
            - name: Apply terraform
              run: |
                terraform apply --auto-approve 
